### PR TITLE
Virtual browse actions

### LINKED ISSUE #10: Virtual Browse covering actions links
The Virtual Browser option is covering the Actions dropdown.  See here:  http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21203370600002486
Click on virtual browse and then try to use the actions menu.

### PR DESCRIPTION
**Pull request by kristianserrano**
- Fixes #10 
- Moves discovere.css into css directory.

Example can be seen in [sandbox](http://discoveretest.emory.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=dedupmrg89060470&indx=10&recIds=dedupmrg89060470&recIdxs=9&elementId=9&renderMode=poppedOut&displayMode=full&frbrVersion=&dscnt=0&mode=Basic&vid=discovere&tab=emory_catalog&vl(28118899UI1)=all_items&dstmp=1502904782445&frbg=&frbrVersion=&viewAllItemsClicked=false&scp.scps=scope%3A%2801EMORY_ALMA%29%2Cscope%3A%28repo%29%2CEmory_PrimoThirdNode&tb=t&srt=rank&dum=true&selectedLocation=&vl(freeText0)=beckett&wroDevMode=true)

### CODE REVIEW

**Comment by kristianserrano** [comment]
@eipeele, do you want me to deploy to production or do you want to?

**Comment by laura-ake** [comment]
Discoveretest first?

**Comment by eipeele** [comment]
@kristianserrano go for it

**Comment by kristianserrano** [comment]
A link to the deployment was included with the pull request above as per the instructions in the readme. @eipeele had reviewed it and approved it. It's ready for deployment to production.

**Comment by laura-ake** [comment]
Thanks ks

**Comment by kristianserrano** [comment]
Deployed to production.

**Pull request merged**
