### PR TITLE
Updates banner for discovere sunday update

### PR DESCRIPTION
**Pull request by eipeele**
This provides the message and the link to the blog for the discovere update on sunday.  Feel free to critique the message and the blog.

I also ran this through a json validator and it checked out.

### CODE REVIEW

**Comment by eipeele** [comment]
So how would you suggest having the link work for screen readers and non-screen readers?

**Comment by kristianserrano** [comment]
[DiscoverE will be Updated on Sunday, September 10th](https://scholarblogs.emory.edu/librarycoreservices/2017/09/07/discovere-update-sunday-september-11th/)

**Comment by eipeele** [comment]
ah, just make the whole thing a link.  okay.

**Comment by kristianserrano** [comment]
Also, lowercase "updated"

**Comment by eipeele** [comment]
I respectfully disagree.  http://web.archive.org/web/20130117225252/http://writersblock.ca/tips/monthtip/tipmar98.htm

**Comment by kristianserrano** [comment]
Oh, sorry, you're correct. I was looking at [my first version of the typed message itself](https://github.com/emory-libraries/discovere-restyle/pull/23#pullrequestreview-61312510), not the heading.

**Comment by eipeele** [comment]
Added changes.  I don't like how the comma shows up with the link, but if that's how it needs to be, that's fine.

**Pull request merged**
